version: '3'
services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: database
      DB_PORT: 3306
      STATE_STORAGE_HOST: state_storage
      STATE_STORAGE_PORT: 6379
    volumes:
      - images:/bot/src/Bot/images
    restart: always
    depends_on:
      - db
      - state_storage
  db:
    image: mariadb
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    container_name: database
  state_storage:
    image: redis:alpine
    restart: on-failure:10
    container_name: state_storage
volumes:
  db-data:
  images:
