version: '3'
services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: bot_db
      DB_PORT: 5432
    restart: always
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    container_name: bot_db
volumes:
  db-data: